"""delete unique option id

Revision ID: a0879e25eef1
Revises: c65f976859de
Create Date: 2025-05-26 00:05:56.639848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0879e25eef1'
down_revision: Union[str, None] = 'c65f976859de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('options_option_id_key', 'options', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('options_option_id_key', 'options', ['option_id'])
    # ### end Alembic commands ###
