"""add uq order+value

Revision ID: 87fe4ffbd9c4
Revises: 08a39133a8aa
Create Date: 2025-05-25 13:22:18.311041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87fe4ffbd9c4"
down_revision: Union[str, None] = "08a39133a8aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_order_code_value", "goods", ["order_code", "value"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_order_code_value", "goods", type_="unique")
    # ### end Alembic commands ###
