"""add status into offers

Revision ID: c06ef4d2b136
Revises: 15a15cc50a55
Create Date: 2025-05-14 17:07:44.604943

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c06ef4d2b136"
down_revision: Union[str, None] = "15a15cc50a55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "offers",
        sa.Column(
            "status", sa.Enum("active", "inactive", name="status"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("offers", "status")
    # ### end Alembic commands ###
