"""add others column in options

Revision ID: c726278698e2
Revises: 6307763b6591
Create Date: 2025-05-26 00:13:55.287691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c726278698e2'
down_revision: Union[str, None] = '6307763b6591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('options', sa.Column('nominal', sa.Float(), nullable=True))
    op.add_column('options', sa.Column('currency', sa.String(), nullable=True))
    op.drop_column('options', 'option_type')
    op.drop_column('options', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('options', sa.Column('option_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('options', 'currency')
    op.drop_column('options', 'nominal')
    op.drop_column('options', 'platform')
    # ### end Alembic commands ###
