"""add goods table

Revision ID: 08a39133a8aa
Revises: e78d67c7cf12
Create Date: 2025-05-21 14:14:07.548910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a39133a8aa'
down_revision: Union[str, None] = 'e78d67c7cf12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_code', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('get_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_code'], ['orders.unique_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    # ### end Alembic commands ###
