"""change status offers model

Revision ID: e78d67c7cf12
Revises: c06ef4d2b136
Create Date: 2025-05-17 17:57:34.697197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e78d67c7cf12"
down_revision: Union[str, None] = "c06ef4d2b136"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("offers", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.drop_column("offers", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "offers",
        sa.Column(
            "status",
            postgresql.ENUM("pending", "processing", "success", "error", name="status"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("offers", "is_active")
    # ### end Alembic commands ###
