"""add unique option id

Revision ID: 6307763b6591
Revises: a0879e25eef1
Create Date: 2025-05-26 00:09:56.086838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6307763b6591'
down_revision: Union[str, None] = 'a0879e25eef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'options', ['option_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'options', type_='unique')
    # ### end Alembic commands ###
