"""add offers table

Revision ID: 15a15cc50a55
Revises: 3152b628a80c
Create Date: 2025-05-13 20:10:09.494372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "15a15cc50a55"
down_revision: Union[str, None] = "3152b628a80c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lot_id", sa.Integer(), nullable=False),
        sa.Column(
            "lot_type",
            sa.Enum("telegram_stars", "steam_cards", "itunes_cards", name="lottype"),
            nullable=False,
        ),
        sa.Column("add_time", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_offers_lot_id"), "offers", ["lot_id"], unique=True)
    op.add_column("orders", sa.Column("lot_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "orders", "offers", ["lot_id"], ["lot_id"])
    op.drop_column("orders", "lot_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("lot_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "lot_id")
    op.drop_index(op.f("ix_offers_lot_id"), table_name="offers")
    op.drop_table("offers")
    # ### end Alembic commands ###
