"""create orders

Revision ID: be4960e8e327
Revises: 
Create Date: 2025-05-06 20:07:01.444517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be4960e8e327'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inv', sa.Integer(), nullable=False),
    sa.Column('unique_code', sa.String(), nullable=False),
    sa.Column('lot_type', sa.String(), nullable=False),
    sa.Column('buyer_email', sa.String(), nullable=False),
    sa.Column('received', sa.Integer(), nullable=False),
    sa.Column('received_currency', sa.String(), nullable=False),
    sa.Column('pay_time', sa.Integer(), nullable=False),
    sa.Column('check_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'success', 'error', name='status'), nullable=False),
    sa.Column('notation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inv'),
    sa.UniqueConstraint('unique_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
